import { type NextPage } from "next";
import Head from "next/head";
import TopStories from "./components/TopStories";
import type { GetStaticProps } from "next";
import MainSection from "./components/MainSection";
import type { Article } from "../../types";
import HeaderNav from "./components/HeaderNav";

type Props = {
  articles: Article[];
};

const Home: NextPage<Props> = ({ articles }) => {
  return (
    <div className="mx-4 md:mx-20 lg:mx-40">
      <Head>
        <title>NC News</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderNav />
      <main>
        <MainSection
          mainStory={articles[0]}
          newStories={articles
            .sort((a, b) => +a.created_at - +b.created_at)
            .slice(0, 3)}
        ></MainSection>

        <TopStories
          topStories={[...articles]
            .sort((a, b) => b.votes - a.votes)
            .slice(0, 3)}
        ></TopStories>
      </main>
    </div>
  );
};
export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(
    "https://nc-news-production.up.railway.app/api/articles"
  );
  const data = (await res.json()) as { articles: Article[] };
  const articles = data.articles;

  return {
    props: {
      articles,
    },
  };
};

export default Home;
